"use strict";jQuery.fn.dsvy_is_bound=function(type){if(this.data('events')!==undefined){if(this.data('events')[type]===undefined||this.data('events')[type].length===0){return!1}
return(-1!==$.inArray(fn,this.data('events')[type]))}else{return!1}};var dsvy_sticky_header=function(){if(jQuery('.dsvy-header-sticky-yes').length>0){var header_html=jQuery('#masthead .dsvy-main-header-area').html();jQuery('.dsvy-sticky-header').append(header_html);jQuery('.dsvy-sticky-header .main-navigation ul, .dsvy-sticky-header .main-navigation ul li, .dsvy-sticky-header .main-navigation ul li a').removeAttr('id');jQuery('.dsvy-sticky-header h1').each(function(){var thisele=jQuery(this);var thisele_class=jQuery(this).attr('class');thisele.replaceWith('<span class="'+thisele_class+'">'+jQuery(thisele).html()+'</span>')});if(jQuery('.dsvy-main-header-area').hasClass('dsvy-infostack-header')){jQuery(".dsvy-sticky-header .dsvy-header-menu-area").insertAfter(".dsvy-sticky-header .site-branding");jQuery('.dsvy-sticky-header .dsvy-header-info, .dsvy-sticky-header .dsvy-mobile-search, .dsvy-sticky-header .nav-menu-toggle').remove();jQuery(".dsvy-sticky-header .dsvy-header-left, .dsvy-sticky-header .dsvy-header-right").remove()}}}
var dsvy_sticky_header_class=function(){if(jQuery('#wpadminbar').length>0){jQuery('#masthead').addClass('dsvy-adminbar-exists')}
var offset_px=300;if(jQuery('.dsvy-main-header-area').length>0){offset_px=jQuery('.dsvy-main-header-area').height()+offset_px}
jQuery(window).scroll(function(){if(jQuery(window).scrollTop()>offset_px){jQuery('#masthead').addClass('dsvy-fixed-header');jQuery('.dsvy-sticky-header .mega-menu.max-mega-menu.mega-menu-horizontal').attr("id","mega-menu-designervily-top")}else{jQuery('#masthead').removeClass('dsvy-fixed-header')}})}
var dsvy_toggleSidebar=function(){jQuery('#menu-toggle').on('click',function(){jQuery("body:not(.mega-menu-designervily-top) .dsvy-navbar > div, body:not(.mega-menu-designervily-top)").toggleClass("active")})
if(jQuery('.dsvy-navbar > div > .closepanel').length==0){jQuery('.dsvy-navbar > div').append('<span class="closepanel"><i class="dsvy-base-icon-cancel-1"></i></span>');jQuery('.dsvy-navbar > div > .closepanel, .mega-menu-designervily-top .nav-menu-toggle').on('click',function(){jQuery(".dsvy-navbar > div, body, .mega-menu-wrap").toggleClass("active")});if(jQuery('.dsvy-main-header-area .dsvy-right-box > .dsvy-cart-wrapper, .dsvy-main-header-area .dsvy-right-box .dsvy-search-cart-box > .dsvy-cart-wrapper').length>0){if(jQuery('.dsvy-navbar > div > .dsvy-responsive-icons').length==0){jQuery('.dsvy-navbar > div').append("<div class='dsvy-responsive-icons'></div>")}
jQuery('.dsvy-navbar > div > .dsvy-responsive-icons').append('<div class="dsvy-cart-wrapper"></div>');jQuery('.dsvy-navbar > div > .dsvy-responsive-icons .dsvy-cart-wrapper').append(jQuery('.dsvy-main-header-area .dsvy-right-box > .dsvy-cart-wrapper, .dsvy-main-header-area .dsvy-right-box .dsvy-search-cart-box > .dsvy-cart-wrapper').html())}
if(jQuery('.dsvy-main-header-area .dsvy-right-box > .dsvy-header-search-btn, .dsvy-main-header-area .dsvy-right-box .dsvy-search-cart-box > .dsvy-header-search-btn').length>0){if(jQuery('.dsvy-navbar > div > .dsvy-responsive-icons').length==0){jQuery('.dsvy-navbar > div').append("<div class='dsvy-responsive-icons'></div>")}
jQuery('.dsvy-navbar > div > .dsvy-responsive-icons').append('<div class="dsvy-header-search-btn"></div>');jQuery('.dsvy-navbar > div > .dsvy-responsive-icons .dsvy-header-search-btn').append(jQuery('.dsvy-main-header-area .dsvy-right-box > .dsvy-header-search-btn, .dsvy-main-header-area .dsvy-right-box .dsvy-search-cart-box > .dsvy-header-search-btn').html())}
return!1}}
function dsvy_wc_cart_page_qty_update(){jQuery(document).ajaxComplete(function(){if(jQuery('.product-quantity .quantity input.input-text.qty').length>0&&jQuery('.dsvy-cart-wrapper .dsvy-cart-details span.dsvy-cart-count').length>0){var total_qty=0;jQuery('.product-quantity .quantity input.input-text.qty').each(function(){total_qty=total_qty+parseInt(jQuery(this).val());jQuery('.dsvy-cart-wrapper .dsvy-cart-details span.dsvy-cart-count').text(total_qty)});jQuery('.dsvy-cart-wrapper span.woocommerce-Price-amount').html(jQuery('.cart_totals .woocommerce-Price-amount > bdi').html())}})}
var dsvy_preloader=function(){jQuery(".dsvy-preloader").fadeOut('600')}
var dsvy_sorting=function(){jQuery('.dsvy-sortable-yes').each(function(){var boxes=jQuery('.dsvy-element-posts-wrapper',this);var links=jQuery('.dsvy-sortable-list a',this);boxes.isotope({animationEngine:'best-available'});links.on('click',function(e){var selector=jQuery(this).data('sortby');if(selector!='*'){var selector='.'+selector}
boxes.isotope({filter:selector,itemSelector:'.dsvy-ele',layoutMode:'fitRows'});links.removeClass('dsvy-selected');jQuery(this).addClass('dsvy-selected');e.preventDefault()})})}
var dsvy_back_to_top=function(){var btn=jQuery('.scroll-to-top');jQuery(window).scroll(function(){if(jQuery(window).scrollTop()>300){btn.addClass('show')}else{btn.removeClass('show')}});btn.on('click',function(e){e.preventDefault();jQuery('html, body').animate({scrollTop:0},'300')})}
var dsvy_navbar=function(){if(!jQuery('ul#dsvy-top-menu > li > a[href="#"]').dsvy_is_bound('click')){jQuery('ul#dsvy-top-menu > li > a[href="#"]').click(function(){return!1})}
jQuery('.dsvy-navbar > div > ul li:has(ul)').append("<span class='sub-menu-toggle'><i class='dsvy-base-icon-down-open-big'></i></span>");jQuery('.dsvy-navbar li').hover(function(){if(jQuery(this).children("ul").length==1){var parent=jQuery(this);var child_menu=jQuery(this).children("ul");if(jQuery(parent).offset().left+jQuery(parent).width()+jQuery(child_menu).width()>jQuery(window).width()){jQuery(child_menu).addClass('dsvy-nav-left')}else{jQuery(child_menu).removeClass('dsvy-nav-left')}}});jQuery(".nav-menu-toggle").on("click tap",function(){dsvy_toggleSidebar()});jQuery('.sub-menu-toggle').on('click',function(){if(jQuery(this).siblings('.sub-menu, .children').hasClass('show')){jQuery(this).siblings('.sub-menu, .children').removeClass('show');jQuery('i',jQuery(this)).removeClass('dsvy-base-icon-up-open-big').addClass('dsvy-base-icon-down-open-big')}else{jQuery(this).siblings('.sub-menu, .children').addClass('show');jQuery('i',jQuery(this)).removeClass('dsvy-base-icon-down-open-big').addClass('dsvy-base-icon-up-open-big')}
return!1});jQuery('.dsvy-navbar ul.menu > li > a').on('click',function(){if(jQuery(this).attr('href')=='#'&&jQuery(this).siblings('ul.sub-menu, ul.children').length>0){jQuery(this).siblings('.sub-menu-toggle').trigger('click');return!1}})}
var dsvy_lightbox=function(){var i_type='image';jQuery('a.dsvy-lightbox, a.dsvy-lightbox-video, .dsvy-lightbox-video a, .dsvy-lightbox a').each(function(){if(jQuery(this).hasClass('dsvy-lightbox-video')||jQuery(this).closest('.elementor-element').hasClass('dsvy-lightbox-video')){i_type='iframe'}else{i_type='image'}
if(jQuery(this).closest('.dsvy-ele-portfolio').length==0){jQuery(this).magnificPopup({type:i_type})}})}
var dsvy_video_popup=function(){jQuery('.dsvy-popup').on('click',function(event){event.preventDefault();var href=jQuery(this).attr('href');var title=jQuery(this).attr('title');window.open(href,title,"width=600,height=500")})}
var dsvy_testimonial=function(){jQuery('.dsvy-testimonial-active').each(function(){var ele_parent=jQuery(this).closest('.dsvy-element-posts-wrapper');jQuery('.designervily-ele.designervily-ele-testimonial',ele_parent).on('mouseover',function(){jQuery('.designervily-ele.designervily-ele-testimonial',ele_parent).removeClass('dsvy-testimonial-active');jQuery(this).addClass('dsvy-testimonial-active')})})}
var dsvy_search_btn=function(){jQuery(function(){jQuery('.dsvy-header-search-btn').on("click",function(event){event.preventDefault();jQuery(".dsvy-header-search-form-wrapper").addClass("open");jQuery('.dsvy-header-search-form-wrapper input[type="search"]').focus()});jQuery(".dsvy-search-close").on("click keyup",function(event){jQuery(".dsvy-header-search-form-wrapper").removeClass("open")})})}
var dsvy_gallery=function(){jQuery("div.dsvy-gallery").each(function(){jQuery(this).lightSlider({item:1,auto:!0,loop:!0,controls:!1,speed:1500,pause:5500})})}
var dsvy_center_logo_header_class=function(){if(jQuery('#masthead.dsvy-header-style-5 ul#dsvy-top-menu').length>0){var has_class=jQuery('#masthead.dsvy-header-style-5 ul#dsvy-top-menu > li').hasClass('dsvy-logo-append');if(has_class==!1){var total_li=jQuery('#masthead.dsvy-header-style-5 ul#dsvy-top-menu > li').length;var li=Math.floor(total_li/2);jQuery('#masthead.dsvy-header-style-5 ul#dsvy-top-menu > li:nth-child('+li+')').addClass('dsvy-logo-append')}}}
var dsvy_selectwrap=function(){jQuery('select').select2({dropdownParent:jQuery('#page')})}
var dsvy_circle_progressbar=function(){jQuery('.dsvy-circle-outer').each(function(){var this_circle=jQuery(this);var emptyFill_val="rgba(0, 0, 0, 0)";var thickness_val=10;var fill_val=this_circle.data('fill');var size_val=110;if(typeof this_circle.data('emptyfill')!=='undefined'&&this_circle.data('emptyfill')!=''){emptyFill_val=this_circle.data('emptyfill')}
if(typeof this_circle.data('thickness')!=='undefined'&&this_circle.data('thickness')!=''){thickness_val=this_circle.data('thickness')}
if(typeof this_circle.data('size')!=='undefined'&&this_circle.data('size')!=''){size_val=this_circle.data('size')}
if(typeof this_circle.data('filltype')!=='undefined'&&this_circle.data('filltype')=='gradient'){fill_val={gradient:[this_circle.data('gradient1'),this_circle.data('gradient2')],gradientAngle:Math.PI/4}}
if(typeof jQuery.fn.circleProgress=="function"){var digit=this_circle.data('digit');var before=this_circle.data('before');var after=this_circle.data('after');var digit=Number(digit);var short_digit=(digit/100);jQuery('.dsvy-circle',this_circle).circleProgress({value:0,size:size_val,startAngle:-Math.PI/4*2,thickness:thickness_val,emptyFill:emptyFill_val,fill:fill_val}).on('circle-animation-progress',function(event,progress,stepValue){this_circle.find('.dsvy-circle-number').html(before+Math.round(stepValue*100)+after)})}
this_circle.waypoint(function(direction){if(!this_circle.hasClass('completed')){if(typeof jQuery.fn.circleProgress=="function"){jQuery('.dsvy-circle',this_circle).circleProgress({value:short_digit})};this_circle.addClass('completed')}},{offset:'85%'})})}
var dsvy_carousel=function(){jQuery(".designervily-element-viewtype-carousel").each(function(){var carouselElement=jQuery(this);jQuery('.dsvy-ele',carouselElement).removeClass(function(index,className){return(className.match(/(^|\s)col-md-\S+/g)||[]).join(' ')}).removeClass(function(index,className){return(className.match(/(^|\s)col-lg-\S+/g)||[]).join(' ')}).removeClass(function(index,className){return(className.match(/(^|\s)wpem-col\S+/g)||[]).join(' ')}).removeClass(function(index,className){return(className.match(/(^|\s)wpem-event-box-col\S+/g)||[]).join(' ')}).removeClass('wpem-col');var columns=jQuery(this).data('columns');var loop=jQuery(this).data('loop');if(columns=='1'){var responsive_items=['1','1','1','1','1']}else if(columns=='2'){var responsive_items=['2','2','2','2','1']}else if(columns=='3'){var responsive_items=['3','2','2','2','1']}else if(columns=='4'){var responsive_items=['4','4','3','2','1']}else if(columns=='5'){var responsive_items=['5','4','3','2','1']}else if(columns=='6'){var responsive_items=['6','4','3','2','1']}else{var responsive_items=['3','3','3','2','1']}
var margin_val=30;if(jQuery(carouselElement).data('margin')!=''){margin_val=jQuery(carouselElement).data('margin')}
var posts_wrapper_class='.dsvy-element-posts-wrapper';var val_nav=jQuery(carouselElement).data('nav');if(val_nav=='above'){val_nav=!1}
var car_options={loop:jQuery(carouselElement).data('loop'),autoplay:jQuery(carouselElement).data('autoplay'),center:jQuery(carouselElement).data('center'),nav:val_nav,dots:jQuery(carouselElement).data('dots'),autoplaySpeed:jQuery(carouselElement).data('autoplayspeed'),autoplayTimeout:jQuery(carouselElement).data('autoplayspeed')+5000,navSpeed:jQuery(carouselElement).data('autoplayspeed'),dotsSpeed:jQuery(carouselElement).data('autoplayspeed'),dragEndSpeed:jQuery(carouselElement).data('autoplayspeed'),margin:30,items:columns,responsiveClass:!0,responsive:{1199:{items:responsive_items[0],},991:{items:responsive_items[1],},767:{items:responsive_items[2],},575:{items:responsive_items[3],},0:{items:responsive_items[4],}}};if(typeof margin_val=="string"&&margin_val!=''){margin_val=margin_val.replace('px','');margin_val=parseInt(margin_val);car_options.margin=margin_val}
var dsvy_owl=jQuery(posts_wrapper_class,carouselElement).removeClass('row multi-columns-row').addClass('owl-carousel').owlCarousel(car_options).removeClass('wpem-row');jQuery('.dsvy-carousel-prev',carouselElement).click(function(event){event.preventDefault();dsvy_owl.trigger('prev.owl.carousel',[jQuery(carouselElement).data('autoplayspeed')])});jQuery('.dsvy-carousel-next',carouselElement).click(function(event){event.preventDefault();dsvy_owl.trigger('next.owl.carousel',[jQuery(carouselElement).data('autoplayspeed')])})})};var dsvy_menu_count=function(){if(jQuery('ul#dsvy-top-menu > li').length>0||jQuery('div#dsvy-top-menu > ul > li').length>0){if(jQuery('ul#dsvy-top-menu > li').length>0){var total_li=jQuery('ul#dsvy-top-menu > li').length}
if(jQuery('div#dsvy-top-menu > ul > li').length>0){var total_li=jQuery('div#dsvy-top-menu > ul > li').length}
if(total_li>6){jQuery('#site-navigation').addClass('dsvy-bigger-menu')}}}
var dsvy_number_rotate=function(){jQuery(".dsvy-number-rotate").each(function(){var self=jQuery(this);var delay=(self.data("appear-animation-delay")?self.data("appear-animation-delay"):0);var animation=self.data("appear-animation");self.html('0');self.waypoint(function(direction){if(!self.hasClass('completed')){var from=self.data('from');var to=self.data('to');var interval=self.data('interval');self.numinate({format:'%counter%',from:from,to:to,runningInterval:2000,stepUnit:interval,onComplete:function(elem){self.addClass('completed')}})}},{offset:'85%'})})};var dsvy_img_size_correction=function(){setTimeout(function(){jQuery("img").each(function(){var thisimg=jQuery(this);var p_width=jQuery(this).parent().width();var width=jQuery(this).attr('width');var height=jQuery(this).attr('height');if((typeof width!==typeof undefined&&width!==!1)&&(typeof height!==typeof undefined&&height!==!1)){var ratio=height/width;jQuery(this).data('dsvy-ratio',ratio);var real_width=jQuery(this).width();var new_height=Math.round(real_width*ratio)}})},100)};var dsvy_tabs_element=function(){var tab_number='';jQuery('.dsvy-tab-link').on('click',function(){if(!jQuery(this).hasClass('dsvy-tab-li-active')){var parent=jQuery(this).closest('ul.dsvy-tabs-heading');jQuery('li',parent).each(function(){jQuery(this).removeClass('dsvy-tab-li-active')});jQuery(this).addClass('dsvy-tab-li-active');tab_number=jQuery(this).data('dsvy-tab');jQuery(this).parent().parent().find('.dsvy-tab-content').removeClass('dsvy-tab-active');jQuery(this).parent().parent().find('.dsvy-tab-content-'+tab_number).addClass('dsvy-tab-active')}});jQuery('.dsvy-tab-content-title').on('click',function(){tab_number=jQuery(this).data('dsvy-tab');jQuery(this).closest('.dsvy-tabs').find('li.dsvy-tab-link[data-dsvy-tab="'+tab_number+'"]',).trigger('click')})};var dsvy_infinite_scroll=function(){if(jQuery('.dsvy-infinite-scroll-yes').length>0){jQuery('.dsvy-infinite-scroll-yes').each(function(){var main_ele=jQuery(this);var style=jQuery(this).data('style');var cpt=jQuery(this).data('cpt');var columns=jQuery(this).data('columns');var show=jQuery(this).data('show');var totalpagination=jQuery(this).data('totalpagination');var infinitre_scroll_data=jQuery('.dsvy-infinite-scroll-data',main_ele).html();if(infinitre_scroll_data!=''){var url_attributes='';jQuery.each(jQuery.parseJSON(infinitre_scroll_data),function(key,value){url_attributes=url_attributes+'&'+key+'='+value})}
if(jQuery(this).hasClass('dsvy-infinite-scroll-button-yes')){var x=2;let $grid=jQuery('.dsvy-element-posts-wrapper',main_ele).masonry({itemSelector:'none',columnWidth:'.dsvy-ele',gutter:0,percentPosition:!0,stagger:30,visibleStyle:{transform:'translateY(0)',opacity:1},hiddenStyle:{transform:'translateY(100px)',opacity:0},});let msnry=$grid.data('masonry');$grid.imagesLoaded(function(){$grid.removeClass('are-images-unloaded');$grid.masonry('option',{itemSelector:'.dsvy-ele'});let $items=$grid.find('.dsvy-ele');$grid.masonry('appended',$items)});$grid.infiniteScroll({path:dsvy_js_variables.ajaxurl+'?action=dsvy_infinite_scroll&page_no={{#}}&nonce='+dsvy_js_variables.ajaxnonce+url_attributes,checkLastPage:!1,button:'.dsvy-ajax-load-more-btn > a',scrollThreshold:!1,status:'.dsvy-infinite-loader',append:'.dsvy-ele',history:!1,visibleStyle:{transform:'translateY(0)',opacity:1},outlayer:msnry,});$grid.on('append.infiniteScroll',function(event,body,path,items,response){jQuery(items).each(function(){jQuery(this).addClass('dsvy-infinite-scroll-animation')});if(x>=totalpagination){jQuery('.dsvy-ajax-load-more-btn > a',main_ele).hide();jQuery('.dsvy-infinite-loader',main_ele).addClass('dsvy-infinite-loader-hide');jQuery('.dsvy-infinite-scroll-last',main_ele).show()}
x++})}else{var x=2;if(x>=totalpagination){jQuery('.dsvy-ajax-load-more-btn > a',main_ele).hide()}
let $grid=jQuery('.dsvy-element-posts-wrapper',main_ele).masonry({itemSelector:'none',columnWidth:'.dsvy-ele',gutter:0,percentPosition:!0,stagger:30,visibleStyle:{transform:'translateY(0)',opacity:1},hiddenStyle:{transform:'translateY(100px)',opacity:0},});let msnry=$grid.data('masonry');$grid.imagesLoaded(function(){$grid.removeClass('are-images-unloaded');$grid.masonry('option',{itemSelector:'.dsvy-ele'});let $items=$grid.find('.dsvy-ele');$grid.masonry('appended',$items)});$grid.infiniteScroll({path:dsvy_js_variables.ajaxurl+'?action=dsvy_infinite_scroll&page_no={{#}}&nonce='+dsvy_js_variables.ajaxnonce+url_attributes,append:'.dsvy-ele',outlayer:msnry,status:'.dsvy-infinite-loader',history:!1,scrollThreshold:-200,});$grid.on('append.infiniteScroll',function(event,body,path,items,response){if(x>=totalpagination){jQuery('.dsvy-infinite-loader',main_ele).addClass('dsvy-infinite-loader-hide');jQuery('.dsvy-infinite-scroll-last',main_ele).show()}
x++})}})}}
var dsvy_searc_results=function(){if(jQuery('.dsvy-search-results-main-wrapper').length>0&&jQuery('.dsvy-search-result-tab-links').length>0){jQuery('.dsvy-search-results-main-wrapper').skeletabs()}
if(jQuery('.dsvy-search-results-main-wrapper').length>0){jQuery('body').addClass('dsvy-search-results-loaded')}}
var dsvy_icon_box_hover_effect=function(){jQuery(".dsvy-icon-box-hover-effect .elementor-container .elementor-top-column").eq(1).addClass('dsvy-ihbox-hover-active');jQuery(".dsvy-icon-box-hover-effect .elementor-container .elementor-top-column").mouseover(function(){var main_row=jQuery(this).closest('.dsvy-icon-box-hover-effect');jQuery('.elementor-top-column',main_row).removeClass('dsvy-ihbox-hover-active');jQuery(this).addClass('dsvy-ihbox-hover-active')})}
var dsvy_multi_icon_box_hover_effect=function(){jQuery(".dsvy-multi-icon-box-hover-effect .dsvy-miconheading-style-8:nth-child(2)").addClass('dsvy-mihbox-hover-active');jQuery(".dsvy-multi-icon-box-hover-effect .dsvy-miconheading-style-8").mouseover(function(){var main_row=jQuery(this).closest('.dsvy-multi-icon-box-hover-effect');jQuery('.dsvy-miconheading-style-8',main_row).removeClass('dsvy-mihbox-hover-active');jQuery(this).addClass('dsvy-mihbox-hover-active')}).mouseout(function(){var main_row=jQuery(this).closest('.dsvy-multi-icon-box-hover-effect');jQuery('.dsvy-miconheading-style-8',main_row).removeClass('dsvy-mihbox-hover-active');jQuery('.dsvy-miconheading-style-8:nth-child(2)',main_row).addClass('dsvy-mihbox-hover-active')})}
var dsvy_validate=function(){jQuery("#commentform").submit(function(event){var error=!1;jQuery('.dsvy-form-error').hide();if(jQuery("#author").length>0&&!jQuery("#author").val()){jQuery('.comment-form-author .dsvy-form-error').show();error=!0}
if(jQuery("#comment").length>0&&!jQuery("#comment").val()){jQuery('.comment-form-comment .dsvy-form-error').show();error=!0}
if(jQuery("#email").length>0){if(!jQuery("#email").val()){jQuery('.comment-form-email .dsvy-form-error.dsvy-empty-email').show();error=!0}else{var valid_email=(/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/.test(jQuery("#email").val()));if(valid_email!=!0){jQuery('.comment-form-email .dsvy-form-error.dsvy-invalid-email').show();error=!0}}}
if(error==!0){event.preventDefault();return!1}else{return!0}})}
jQuery(window).resize(function(){dsvy_img_size_correction()});jQuery(document).ready(function(){dsvy_validate();dsvy_searc_results();dsvy_tabs_element();dsvy_toggleSidebar();dsvy_sorting();dsvy_back_to_top();dsvy_sticky_header();dsvy_navbar();dsvy_lightbox();dsvy_video_popup();dsvy_testimonial();dsvy_search_btn();dsvy_center_logo_header_class();dsvy_selectwrap();dsvy_menu_count();setTimeout(function(){dsvy_carousel()},200);dsvy_img_size_correction();dsvy_number_rotate();dsvy_sticky_header_class();dsvy_icon_box_hover_effect();dsvy_multi_icon_box_hover_effect();dsvy_wc_cart_page_qty_update()});jQuery(window).load(function(){dsvy_preloader();dsvy_sorting();dsvy_gallery();dsvy_circle_progressbar();dsvy_infinite_scroll()})